# Generated by Django 2.2.7 on 2019-12-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel_attr',
            fields=[
                ('Lattitude', models.FloatField(help_text='Latitude of Squirrel', max_length=40)),
                ('Longitude', models.FloatField(help_text='Longitude of Squirrel', max_length=40)),
                ('Squirrel_ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=4)),
                ('Date', models.DateField(help_text='Date spotted')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', '')], max_length=16, null=True)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('', '')], max_length=16, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('', '')], max_length=40, null=True)),
                ('Specific_Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Running', models.BinaryField(null=True)),
                ('Chasing', models.BinaryField(null=True)),
                ('Climbing', models.BinaryField(null=True)),
                ('Eating', models.BinaryField(null=True)),
                ('Foraging', models.BinaryField(null=True)),
                ('Other_Activities', models.TextField(blank=True)),
                ('Kuks', models.BinaryField(null=True)),
                ('Quaas', models.BinaryField(null=True)),
                ('Moans', models.BinaryField(default=False, null=True)),
                ('Tail_flags', models.BinaryField(null=True)),
                ('Tail_twitches', models.BinaryField(null=True)),
                ('Approaches', models.BinaryField(null=True)),
                ('Indifferent', models.BinaryField(null=True)),
                ('Runs_from', models.BinaryField(null=True)),
            ],
        ),
    ]
