# Generated by Django 2.2.7 on 2019-12-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0012_auto_20191205_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel_attr',
            name='Other_Activities',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
